Traceback (most recent call last):
  File "c:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\maria\appdata\local\programs\python\python37-32\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "c:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Importamos las librer√≠as principales
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import pickle
import argparse
import os.path

# De scikit-learn importamos herramientas
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
# Y los clasificadores
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.neural_network import MLPClassifier
from sklearn.cluster import KMeans

# Lo necesario para construir el modelo de tensorflow
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import callbacks
from tensorflow.keras.models import load_model
from tensorflow.keras.models import Model

# Funciones de benchtools
from benchtools.src.plotools import pred_test_hist, image_grid
from benchtools.src.clustering import build_features
from benchtools.src.datatools import separate_data
from benchtools.scripts.run import TensorflowClassifier, training, evaluate
from benchtools.src.metrictools import rejection_plot, precision_recall_plot

# Definimos semillas para la reproducibilidad
tf.random.set_seed(125)

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_8732/3617788364.py[0m in [0;36m<module>[1;34m[0m
[0;32m     19[0m [1;33m[0m[0m
[0;32m     20[0m [1;31m# Lo necesario para construir el modelo de tensorflow[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 21[1;33m [1;32mimport[0m [0mtensorflow[0m [1;32mas[0m [0mtf[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     22[0m [1;32mfrom[0m [0mtensorflow[0m [1;32mimport[0m [0mkeras[0m[1;33m[0m[1;33m[0m[0m
[0;32m     23[0m [1;32mfrom[0m [0mtensorflow[0m[1;33m.[0m[0mkeras[0m [1;32mimport[0m [0mlayers[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'tensorflow'
ModuleNotFoundError: No module named 'tensorflow'

